In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [5]:
arr1 + arr2

array([5, 7, 9])

In [6]:
arr = np.array([1,2,3,4,5,6])

In [7]:
arr[-2]

5

In [8]:
arr[2]

3

In [9]:
arr[0:3]

array([1, 2, 3])

In [10]:
arr.shape

(6,)

In [11]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

In [13]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [16]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

In [17]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [18]:
np.mean(arr)

3.5

In [19]:
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
np.std(arr)

1.707825127659933

In [23]:
np.random.rand(10)

array([0.73778667, 0.39469168, 0.78242418, 0.61801286, 0.65882149,
       0.10950507, 0.24289087, 0.17296371, 0.72119706, 0.15127337])

In [24]:
arr = [1,2,3,np.nan,5,6]

In [25]:
arr

[1, 2, 3, nan, 5, 6]

In [26]:
np.isnan(arr)

array([False, False, False,  True, False, False])

In [2]:
import time

In [3]:
ls1 = list(range(1000))
start = time.time()
sum(ls1)
end=time.time()
print(end-start)

9.393692016601562e-05


In [4]:
start = time.time()
np.sum(ls1)
end=time.time()
print(end-start)

NameError: name 'np' is not defined